## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Mat Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Por Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Geo Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Ing Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['His Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Fis Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qui Qt_acertos'])

In [3]:
# 1) Seu código aqui
tabela_geral = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis=1)


tabela_porcentagem = pd.DataFrame()
tabela_porcentagem['Mat'] = (df_mat/24)*100
tabela_porcentagem['Por'] = (df_por/18)*100
tabela_porcentagem['Geo'] = (df_geo/8)*100
tabela_porcentagem['Ing'] = (df_ing/8)*100
tabela_porcentagem['His'] = (df_his/8)*100
tabela_porcentagem['Fis'] = (df_fis/12)*100
tabela_porcentagem['Qui'] = (df_qui/12)*100

tabela_porcentagem

          Mat        Por   Geo   Ing   His        Fis        Qui
0   25.000000  38.888889  87.5  37.5  12.5  66.666667  25.000000
1   79.166667  55.555556   0.0   0.0   0.0  91.666667  66.666667
2   58.333333  88.888889   0.0  62.5  87.5  33.333333  33.333333
3   41.666667  38.888889  37.5  50.0   0.0   0.000000  66.666667
4   29.166667  11.111111  25.0  87.5   0.0  75.000000  25.000000
..        ...        ...   ...   ...   ...        ...        ...
95  25.000000  22.222222  87.5  12.5  50.0  75.000000  25.000000
96  33.333333   5.555556  50.0  75.0  12.5  33.333333  25.000000
97  95.833333  27.777778   0.0  25.0  50.0   8.333333  41.666667
98   0.000000  55.555556  37.5  12.5  62.5  83.333333  91.666667
99  45.833333  83.333333   0.0  12.5  75.0  58.333333  16.666667

[100 rows x 7 columns]

In [4]:
# 2) Seu código aqui
tabela_geral['Acertos'] = (tabela_geral['Mat Qt_acertos'] +
                           tabela_geral['Por Qt_acertos'] +
                           tabela_geral['Geo Qt_acertos'] +
                           tabela_geral['Ing Qt_acertos'] +
                           tabela_geral['His Qt_acertos'] +
                           tabela_geral['Fis Qt_acertos'] +
                           tabela_geral['Qui Qt_acertos'])
tabela_geral

,Mat Qt_acertos,Por Qt_acertos,Geo Qt_acertos,Ing Qt_acertos,His Qt_acertos,Fis Qt_acertos,Qui Qt_acertos,Acertos
0,6,7,7,3,1,8,3,35
1,19,10,0,0,0,11,8,48
2,14,16,0,5,7,4,4,50
3,10,7,3,4,0,0,8,32
4,7,2,2,7,0,9,3,30
...,...,...,...,...,...,...,...,...
95,6,4,7,1,4,9,3,34
96,8,1,4,6,1,4,3,27
97,23,5,0,2,4,1,5,40
98,0,10,3,1,5,10,11,40
99,11,15,0,1,6,7,2,42

In [5]:
# 3) Seu código aqui
tabela_porcentagem['Total']= (tabela_porcentagem['Mat'] +
                                tabela_porcentagem['Por'] +
                                tabela_porcentagem['Geo'] +
                                tabela_porcentagem['Ing'] +
                                tabela_porcentagem['His'] +
                                tabela_porcentagem['Fis'] +
                                tabela_porcentagem['Qui'] )

tabela_porcentagem['media'] = tabela_porcentagem['Total']/7
tabela_porcentagem

,Mat,Por,Geo,Ing,His,Fis,Qui,Total,media
0,25.000000,38.888889,87.5,37.5,12.5,66.666667,25.000000,293.055556,41.865079
1,79.166667,55.555556,0.0,0.0,0.0,91.666667,66.666667,293.055556,41.865079
2,58.333333,88.888889,0.0,62.5,87.5,33.333333,33.333333,363.888889,51.984127
3,41.666667,38.888889,37.5,50.0,0.0,0.000000,66.666667,234.722222,33.531746
4,29.166667,11.111111,25.0,87.5,0.0,75.000000,25.000000,252.777778,36.111111
...,...,...,...,...,...,...,...,...,...
95,25.000000,22.222222,87.5,12.5,50.0,75.000000,25.000000,297.222222,42.460317
96,33.333333,5.555556,50.0,75.0,12.5,33.333333,25.000000,234.722222,33.531746
97,95.833333,27.777778,0.0,25.0,50.0,8.333333,41.666667,248.611111,35.515873
98,0.000000,55.555556,37.5,12.5,62.5,83.333333,91.666667,343.055556,49.007937
99,45.833333,83.333333,0.0,12.5,75.0,58.333333,16.666667,291.666667,41.666667

In [6]:
# 4) Seu código aqui
aprovados = tabela_porcentagem['media'] >= 45
quantidade_aprovados = aprovados.sum()
quantidade_aprovados

49

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [8]:
# seu código aqui
tabela_geral['Reprovados'] = tabela_geral.apply(
    lambda row: True if (row['Mat Qt_acertos'] == 0 or row['Fis Qt_acertos'] == 0 or row['Qui Qt_acertos'] == 0) else False,
    axis=1
)
reprovados = tabela_geral['Reprovados'] == True
quantidade_reprovados = reprovados.sum()
quantidade_reprovados
## alunos que reprovaram em uma das matérias que desqualificam o candidato são 23

23

In [9]:
indices_reprovados = tabela_geral[tabela_geral['Reprovados'] == True].index

df_porcentagem_reprovados_his_geo = tabela_porcentagem.loc[indices_reprovados, ['His', 'Geo']]

df_porcentagem_reprovados_his_geo

     His   Geo
3    0.0  37.5
6   62.5  87.5
10  12.5  37.5
12  12.5  37.5
14  12.5  12.5
20  75.0  75.0
25   0.0  87.5
26  87.5  75.0
27  87.5  12.5
33  75.0   0.0
35  37.5  75.0
49  12.5  12.5
56  75.0  87.5
65  37.5  25.0
66  37.5  37.5
72  87.5  37.5
73  37.5  25.0
74  62.5   0.0
84  12.5   0.0
89  75.0  87.5
92  12.5  12.5
94  12.5  25.0
98  62.5  37.5

In [10]:
aprovados_indice = tabela_geral[tabela_geral['Reprovados'] == False].index
df_porcentagem_aprovados = tabela_porcentagem.loc[aprovados_indice]
df_real_aprovados = df_porcentagem_aprovados[df_porcentagem_aprovados['media']>=45]
df_real_aprovados
#neste caso de acordo com os critérios, se o candidato não acertar nenhuma questão de matematica, fisica e quimica. 
#O mesmo está desclassificado, porém quem está abaixo dos 45% também é desclassificado
#O df abaixo contempla os alunos que não zeraram nas matérias priomordiais e ficaram acima de 45%

,Mat,Por,Geo,Ing,His,Fis,Qui,Total,media
2,58.333333,88.888889,0.0,62.5,87.5,33.333333,33.333333,363.888889,51.984127
5,83.333333,11.111111,62.5,37.5,25.0,75.000000,75.000000,369.444444,52.777778
7,75.000000,22.222222,50.0,87.5,87.5,8.333333,66.666667,397.222222,56.746032
8,91.666667,50.000000,25.0,87.5,75.0,41.666667,58.333333,429.166667,61.309524
9,41.666667,33.333333,37.5,75.0,50.0,66.666667,16.666667,320.833333,45.833333
17,87.500000,83.333333,25.0,25.0,50.0,16.666667,50.000000,337.500000,48.214286
18,83.333333,22.222222,37.5,62.5,37.5,91.666667,33.333333,368.055556,52.579365
19,4.166667,11.111111,87.5,75.0,12.5,75.000000,91.666667,356.944444,50.992063
24,83.333333,11.111111,87.5,62.5,37.5,91.666667,16.666667,390.277778,55.753968
28,45.833333,11.111111,87.5,87.5,62.5,33.333333,25.000000,352.777778,50.396825
29,66.666667,0.000000,0.0,25.0,87.5,91.666667,66.666667,337.500000,48.214286
31,62.500000,72.222222,37.5,12.5,37.5,75.000000,83.333333,380.555556,54.365079
36,91.666667,50.000000,75.0,75.0,12.5,33.333333,66.666667,404.166667,57.738095
37,79.166667,66.666667,62.5,87.5,12.5,50.000000,16.666667,375.000000,53.571429
39,16.666667,88.888889,25.0,50.0,75.0,75.000000,66.666667,397.222222,56.746032
40,75.000000,16.666667,75.0,37.5,75.0,41.666667,50.000000,370.833333,52.976190
41,25.000000,22.222222,37.5,50.0,62.5,33.333333,91.666667,322.222222,46.031746
42,83.333333,33.333333,87.5,87.5,25.0,25.000000,25.000000,366.666667,52.380952
44,25.000000,77.777778,87.5,37.5,12.5,25.000000,75.000000,340.277778,48.611111
45,70.833333,55.555556,0.0,25.0,75.0,75.000000,33.333333,334.722222,47.817460
46,12.500000,16.666667,37.5,87.5,62.5,75.000000,33.333333,325.000000,46.428571
48,70.833333,33.333333,0.0,87.5,62.5,75.000000,91.666667,420.833333,60.119048
51,4.166667,66.666667,87.5,37.5,62.5,33.333333,83.333333,375.000000,53.571429
53,58.333333,61.111111,37.5,50.0,37.5,58.333333,25.000000,327.777778,46.825397
55,45.833333,55.555556,50.0,50.0,62.5,8.333333,50.000000,322.222222,46.031746
60,66.666667,44.444444,0.0,50.0,50.0,58.333333,75.000000,344.444444,49.206349
62,70.833333,33.333333,25.0,50.0,87.5,8.333333,75.000000,350.000000,50.000000
64,12.500000,38.888889,87.5,62.5,37.5,91.666667,16.666667,347.222222,49.603175
67,87.500000,0.000000,87.5,25.0,50.0,16.666667,83.333333,350.000000,50.000000
68,37.500000,50.000000,62.5,37.5,75.0,83.333333,8.333333,354.166667,50.595238
69,12.500000,61.111111,87.5,0.0,37.5,33.333333,91.666667,323.611111,46.230159
70,87.500000,77.777778,0.0,37.5,62.5,91.666667,66.666667,423.611111,60.515873
71,70.833333,44.444444,87.5,75.0,50.0,16.666667,75.000000,419.444444,59.920635
75,12.500000,33.333333,87.5,75.0,75.0,75.000000,41.666667,400.000000,57.142857
77,62.500000,11.111111,62.5,87.5,75.0,91.666667,58.333333,448.611111,64.087302
78,58.333333,88.888889,87.5,25.0,87.5,91.666667,75.000000,513.888889,73.412698
80,54.166667,88.888889,62.5,12.5,87.5,16.666667,8.333333,330.555556,47.222222
81,91.666667,88.888889,25.0,0.0,50.0,8.333333,83.333333,347.222222,49.603175
82,29.166667,88.888889,87.5,12.5,12.5,16.666667,75.000000,322.222222,46.031746
83,83.333333,5.555556,62.5,75.0,37.5,50.000000,8.333333,322.222222,46.031746
88,83.333333,5.555556,12.5,62.5,87.5,75.000000,58.333333,384.722222,54.960317
93,50.000000,88.888889,62.5,62.5,75.0,50.000000,50.000000,438.888889,62.698413

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [67]:
arquivo = './part-00000-f8e7c5f3-6dd8-48ef-95d0-351ecfe18459.c000.csv'
df = pd.read_csv(arquivo, sep=';')
df.head(5)

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,9fb3828d-aca2-42e4-a36e-54fddb1a9b3e-i0b0,bfbce5ed7e31c3dd94f79bf97f2d257dff2777ec9eb7a4...,25,1996-05-12,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/28290,2022-02-17,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
1,dd097975-d896-4adc-97a1-5de3f51792a4-i0b0,5310f2da2074b4d20620f811323a6f7c4fc8853fc5a41f...,22,1998-08-09,F,99,SEM INFORMACAO,120013.0,10.0,BUJARI,...,2.0,Faixa Etária,FA9096,PFIZER,Organization/00394544000851,2021-07-23,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
2,09ed4a47-931d-4c26-bdae-dfebd9e6692f-i0b0,bc79d190041c848e8bf1e50afa31f9e6418eeb3704de79...,19,2002-12-03,M,3,PARDA,120045.0,10.0,SENADOR GUIOMARD,...,2.0,Faixa Etária,FJ4187,PFIZER,Organization/28290,2022-01-10,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
3,dd180d26-5bee-44d5-a4d5-ea314976d7f1-i0b0,d0a264fe07e8b95225c45d61cd6f1c020c1dec5d5f1125...,68,1953-03-01,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FH4750,PFIZER,Organization/28290,2021-11-25,Reforço,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
4,26621638-c2cb-4f49-87ff-253197cfc100-i0b0,db8bedfd8ffc871cd434076c177bf2ab5f702cf976b0d5...,13,2008-04-17,F,4,AMARELA,120070.0,10.0,XAPURI,...,114.0,Outros,FA9096,PFIZER,Organization/00394544000851,2021-08-04,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [101]:
# 1) Sua solução aqui
contagem = df['vacina_codigo'].unique()
print(len(contagem))
#são 13 tipos diferentes de vacinas

13

In [175]:
# 2)
id_unico = df['paciente_id'].unique()
print(len(id_unico))
#No total são 318850 de 390911 (podemos dizer que tem id's repetidos)

318850

In [177]:
# 3)
primeira_dose = df[df['vacina_descricao_dose'] == '1ª Dose']
pacientes_unicos = primeira_dose['paciente_id'].unique()
print(len(pacientes_unicos))

143753

In [16]:
# 3) solução alternativa

In [181]:
# 4)
pacientes_menor = df[df['paciente_idade']<18]
print(len(pacientes_menor))

79220

In [189]:
# 5)
estabelecimento = df['estabelecimento_razaoSocial'].unique()
print(len(estabelecimento))

64

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [205]:
# 1)
indice_pacientes_menores = pacientes_menor.index
df_copia = pd.DataFrame()
df_copia = df.loc[indice_pacientes_menores]
df_copia.head(5)

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
4,26621638-c2cb-4f49-87ff-253197cfc100-i0b0,db8bedfd8ffc871cd434076c177bf2ab5f702cf976b0d5...,13,2008-04-17,F,4,AMARELA,120070.0,10.0,XAPURI,...,114.0,Outros,FA9096,PFIZER,Organization/00394544000851,2021-08-04,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
19,ddbe8e75-ac1e-40b7-ad55-ead506189efd-i0b0,4a502fc943b8e62deca3f6cd1be3885f7b0d8a2ed88796...,14,2007-03-13,F,3,PARDA,120010.0,10.0,BRASILEIA,...,2.0,Faixa Etária,FF5107,PFIZER,Organization/00394544000851,2021-09-30,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
22,bf5bec1c-cf42-4ddd-bfe7-c4632d6475ab-i0b0,39c3b1b701bf1f438f01fa5eafaba700bf901d230827cf...,13,2009-05-25,M,4,AMARELA,120060.0,10.0,TARAUACA,...,2.0,Faixa Etária,FP8073,PFIZER,Organization/28290,2022-05-26,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
26,a93490d2-735a-4bc9-bf8c-b6fc0922344a-i0b0,b75298c39cb90c5d00955f9929be12b1660fa3df5e77e8...,6,2017-12-13,M,99,SEM INFORMACAO,130350.0,10.0,PAUINI,...,2.0,Faixa Etária,230165,BUTANTAN,152,2024-01-23,Única,33,INF3,Novo PNI
46,b743ae06-b10c-4741-871e-7565ff90cebc-i0b0,bf14ca2b448eab7fb3d531325e024ac7564450dabee593...,14,2007-08-13,M,3,PARDA,120013.0,10.0,BUJARI,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/28290,2022-02-19,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [213]:
# 2)

lista_colunas = df_copia.columns.tolist()
lista_colunas

['document_id',
 'paciente_id',
 'paciente_idade',
 'paciente_dataNascimento',
 'paciente_enumSexoBiologico',
 'paciente_racaCor_codigo',
 'paciente_racaCor_valor',
 'paciente_endereco_coIbgeMunicipio',
 'paciente_endereco_coPais',
 'paciente_endereco_nmMunicipio',
 'paciente_endereco_nmPais',
 'paciente_endereco_uf',
 'paciente_endereco_cep',
 'paciente_nacionalidade_enumNacionalidade',
 'estabelecimento_valor',
 'estabelecimento_razaoSocial',
 'estalecimento_noFantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf',
 'vacina_grupoAtendimento_codigo',
 'vacina_grupoAtendimento_nome',
 'vacina_categoria_codigo',
 'vacina_categoria_nome',
 'vacina_lote',
 'vacina_fabricante_nome',
 'vacina_fabricante_referencia',
 'vacina_dataAplicacao',
 'vacina_descricao_dose',
 'vacina_codigo',
 'vacina_nome',
 'sistema_origem']

In [222]:
# 3)
contagem_vacinas = df_copia['vacina_categoria_nome'].value_counts()
contagem_vacinas

vacina_categoria_nome
Faixa Etária                                      49015
Povos Indígenas                                    4934
Outros                                             3755
Povos e Comunidades Tradicionais                    875
Trabalhadores de Saúde                              264
Comorbidades                                         58
População Privada de Liberdade                       53
Gestantes                                            47
Trabalhadores da Educação                            14
Trabalhadores de Transporte                          13
Pessoas com Deficiência                              11
Pessoas Institucionalizadas                           3
Pessoas de 60 anos ou mais institucionalizadas        1
Puérperas                                             1
Name: count, dtype: int64

In [226]:
# 4)
colunas_estabelecimento = [
    'estabelecimento_valor', 
    'estabelecimento_razaoSocial', 
    'estalecimento_noFantasia', 
    'estabelecimento_municipio_codigo', 
    'estabelecimento_municipio_nome', 
    'estabelecimento_uf'
]
colunas_estabelecimento

['estabelecimento_valor',
 'estabelecimento_razaoSocial',
 'estalecimento_noFantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf']

In [230]:
# 5)
df_estabelecimentos = df_copia.loc[:, colunas_estabelecimento]


df_estabelecimentos_unicos = df_estabelecimentos.drop_duplicates()


df_vacinas_por_estabelecimento = df_copia.groupby('estabelecimento_valor').size().reset_index(name='quantidade_vacinas_menores_18')


df_resultado = pd.merge(df_estabelecimentos_unicos, df_vacinas_por_estabelecimento, on='estabelecimento_valor')


df_resultado

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf,quantidade_vacinas_menores_18
0,2001217,PREFEITURA MUNICIPAL DE XAPURI,UNIDADE SAUDE DA FAMILIA JOSE FADUL,120070,XAPURI,AC,1094
1,2001349,PREFEITURA MUNICIPAL DE BRASILEIA,ESF TUFIC MIZAEL SAADY,120010,BRASILEIA,AC,1166
2,3810771,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE DE S DA FAMILIA DR JOSE LEONCIO GOMES ...,120060,TARAUACA,AC,3621
3,7110065,PREFEITURA MUNICIPAL DE RIO BRANCO,USF GENTIL PERDOMO DA ROCHA,120040,RIO BRANCO,AC,88
4,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC,25593
...,...,...,...,...,...,...,...
208,2001357,SECRETARIA MUNICIPAL DE SAUDE DE BRASILEIA,ESF PEDRO OLIVEIRA DE SOUZA,120010,BRASILEIA,AC,4
209,4646770,USF SAO FRANCISCO,USF SAO FRANCISCO,120040,RIO BRANCO,AC,2
210,6411312,PREFEITURA MUNICIPAL DE PLACIDO DE CASTRO,U S F LUCIO ALVES DA SILVA,120038,PLACIDO DE CASTRO,AC,1
211,2000814,SECRETARIA DE ESTADO DE SAUDE DO ACRE,USF FRANCISCO EDUARDO DE PAIVA,120040,RIO BRANCO,AC,2
212,2832798,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,UNIDADE DE SAUDE ALBERTO FLORENCIO DA SILVA,120025,EPITACIOLANDIA,AC,1